regions = ["Western",
          "Central",
          "Greater Accra",
          "Volta",
          "Eastern",
          "Ashanti",
          "Western North",
          "Ahafo",
          "Bono",
          "Bono East",
          "Oti",
          "Northern",
          "Savannah",
          "North East",
          "Upper East",
          "Upper West"
        ]

districts = [
          "Jomoro Municipal",
          "Ellembelle",
          "Nzema East Municipal",
          "Ahanta West Municipal",
          "Effia Kwesimintsim Municipal",
          "Sekondi Takoradi Metropolitan Area (STMA)",
          "STMA-Takoradi",
          "STMA-Sekondi",
          "STMA-Essikado-Ketan",
          "Shama",
          "Wassa East",
          "Mpohor",
          "Tarkwa-Nsuaem Municipal",
          "Prestea/Huni Valley Municipal",
          "Wassa Amenfi East Municipal",
          "Wassa Amenfi Central",
          "Wassa Amenfi West Municipal",
          "Komenda Edina Eguafo Abirem Municipal",
          "Cape Cape Metropolitan Area (CCMA)",
          "CCMA-Cape Coast South",
          "CCMA-Cape Coast North",
          "Abura Asebu Kwamankese",
          "Mfantsiman Municipal",
          "Ekumfi",
          "Gomoa West",
          "Effutu Municipal",
          "Gomoa Central",
          "Gomoa East",
          "Awutu Senya East Municipal",
          "Awutu Senya",
          "Agona East",
          "Agona West Municipal",
          "Asikuma Odoben Brakwa",
          "Ajumako Enyan Essiam",
          "Assin South",
          "Twifo Heman Lower Denkyira",
          "Twifo Ati Morkwa",
          "Assin Fosu Municipal",
          "Assin North",
          "Upper Denkyira East Municipal",
          "Upper Denkyira West",
          "Ga South Municipal",
          "Weija Gbawe Municipal",
          "Ga Central Municipal",
          "Ablekuma North Municipal",
          "Ablekuma West Municipal",
          "Ablekuma Central Municipal",
          "Accra Metropolitan Area (AMA)",
          "AMA-Ablekuma South",
          "AMA-Ashiedu Keteke",
          "AMA-Okaikoi South",
          "Korle Klottey Municipal",
          "Ayawaso Central Municipal",
          "Ayawaso East Municipal",
          "Ayawaso North Municipal",
          "La Dade-Kotopon Municipal",
          "Ledzokuku Municipal",
          "Krowor Municipal",
          "Adentan Municipal",
          "Ayawaso West Municipal",
          "Okaikoi North Municipal",
          "Ga North Municipal",
          "Ga West Municipal",
          "Ga East Municipal",
          "La Nkwantanang Madina Municipal",
          "Kpone Katamanso Municipal",
          "Ashaiman Municipal",
          "Tema West Municipal",
          "Tema Metropolitan Area (TMA)",
          "TMA-Tema Central",
          "TMA-Tema East",
          "Ningo-Prampram",
          "Shai-Osudoku",
          "Ada West",
          "Ada East",
          "South Tongu",
          "Anloga",
          "Keta Municipal",
          "Ketu South Municipal",
          "Ketu North Municipal",
          "Akatsi North",
          "Akatsi South Municipal",
          "Central Tongu",
          "North Tongu",
          "Ho West",
          "Adaklu",
          "Agortime-Ziope",
          "Ho Municipal",
          "South Dayi",
          "Afadzato South",
          "North Dayi",
          "Kpando Municipal",
          "Hohoe Municipal",
          "Birim South",
          "Birim Central Municipal",
          "Achiase",
          "Asene Manso Akroso",
          "West Akim Municipal",
          "Upper West Akim",
          "Ayensuano",
          "Nsawam Adoagyiri Municipal",
          "Akwapim South Municipal",
          "Akwapim North Municipal",
          "Okere",
          "New Juaben South Municipal",
          "New Juaben North Municipal",
          "Suhum Municipal",
          "Abuakwa North Municipal",
          "Abuakwa South Municipal",
          "Denkyembuor",
          "Akyemansa",
          "Kwaebibirem Municipal",
          "Birim North",
          "Atiwa West",
          "Atiwa East",
          "Fanteakwa South",
          "Yilo Krobo Municipal",
          "Lower Manya Krobo Municipal",
          "Asuogyaman",
          "Upper Manya Krobo",
          "Fanteakwa North",
          "Kwahu South Municipal",
          "Kwahu West Municipal",
          "Kwahu East",
          "Kwahu Afram Plains South",
          "Kwahu Afram Plains North",
          "Amansie South",
          "Amansie Central",
          "Akrofuom",
          "Adansi South",
          "Adansi Asokwa",
          "Obuasi East",
          "Obuasi Municipal",
          "Adansi North",
          "Bekwai Municipal",
          "Amansie West",
          "Atwima Kwanwoma",
          "Bosomtwi",
          "Bosome Freho",
          "Asante Akim Central Municipal",
          "Asante Akim South Municipal",
          "Asante Akim North Municipal",
          "Sekyere Kumawu",
          "Sekyere East",
          "Juaben Municipal",
          "Ejisu Municipal",
          "Oforikrom Municipal",
          "Asokwa Municipal",
          "Kumasi Metropolitan Area (KMA)",
          "KMA-Nhyiaeso",
          "KMA-Subin",
          "KMA-Manhyia South",
          "KMA-Manhyia North",
          "KMA-Bantama",
          "Kwadaso Municipal",
          "Suame Municipal",
          "Old Tafo Municipal",
          "Asokore Mampong Municipal",
          "Kwabre East",
          "Afigya Kwabre South",
          "Atwima Nwabiagya North",
          "Atwima Nwabiagya South Municipal",
          "Atwima Mponua",
          "Ahafo Ano South West",
          "Ahafo Ano North Municipal",
          "Ahafo Ano South East",
          "Offinso North",
          "Offinso Municipal",
          "Afigya Kwabre North",
          "Sekyere South",
          "Mampong Municipal",
          "Ejura Sekyedumase Municipal",
          "Sekyere Central",
          "Sekyere Afram Plains",
          "Aowin Municipal",
          "Sefwi Akontombra",
          "Suaman",
          "Bodi",
          "Sefwi Wiawso Municipal",
          "Bibiani Anhwiaso Bekwai Municipal",
          "Juaboso",
          "Bia West",
          "Bia East",
          "Asunafo South",
          "Asunafo North Municipal",
          "Asutifi South",
          "Asutifi North",
          "Tano North Municipal",
          "Tano South Municipal",
          "Dormaa West",
          "Dormaa Central Municipal",
          "Dormaa East",
          "Sunyani Municipal",
          "Sunyani West Municipal",
          "Berekum East Municipal",
          "Berekum West",
          "Jaman South",
          "Jaman North",
          "Tain",
          "Wenchi Municipal",
          "Banda",
          "Nkoranza South Municipal",
          "Techiman Municipal",
          "Nkoranza North",
          "Techiman North",
          "Atebubu Amantin Municipal",
          "Sene West",
          "Sene East",
          "Pru West",
          "Pru East",
          "Kintampo South",
          "Kintampo North Municipal",
          "Biakoye",
          "Jasikan Municipal",
          "Kadjebi",
          "Krachi East Municipal",
          "Krachi West Municipal",
          "Krachi Nchumuru",
          "Nkwanta South Municipal",
          "Nkwanta North (Kpassa)",
          "Guan",
          "Kpandai",
          "Nanumba South",
          "Nanumba North Municipal",
          "Zabzugu",
          "Tatale Sanguli",
          "Saboba",
          "Yendi Municipal",
          "Mion",
          "Nanton",
          "Tamale Metropolitan Area (TMA)",
          "TMA-Tamale South",
          "TMA-Tamale Central",
          "Sagnarigu Municipal",
          "Tolon",
          "Kumbungu",
          "Savelugu Municipal",
          "Karaga",
          "Gushegu Municipal",
          "Bole",
          "Sawla Tuna Kalba",
          "North Gonja",
          "West Gonja",
          "Central Gonja",
          "East Gonja Municipal",
          "North East Gonja",
          "Mamprugu Moagduri",
          "West Mamprusi Municipal",
          "East Mamprusi Municipal",
          "Bunkpurugu Nakpanduri",
          "Yunyoo Nasuan",
          "Chereponi",
          "Builsa South",
          "Builsa North Municipal",
          "Kasena Nankana Municipal",
          "Kasena Nankana West",
          "Bolgatanga Municipal",
          "Talensi",
          "Bolgatanga East",
          "Bongo",
          "Nabdam",
          "Bawku West",
          "Binduri",
          "Bawku Municipal",
          "Garu",
          "Tempane",
          "Pusiga",
          "Wa West",
          "Wa East",
          "Wa Municipal",
          "Nadowli Kaleo",
          "Daffiama Bussie Issa",
          "Sissala East Municipal",
          "Sissala West",
          "Jirapa Municipal",
          "Lawra Municipal",
          "Lambussie Karni",
          "Nandom"
        ]

education = [
        "Never attended",
          "Nursery",
          "Kindergarten",
          "Primary",
          "JSS/JHS",
          "Middle",
          "SSS/SHS",
          "Secondary",
          "Voc/technical/commercial",
          "Post middle/secondary Certificate",
          "Post middle/secondary Diploma",
          "Tertiary/HND",
          "Tertiary - Bachelor's Degree",
          "Tertiary - Post graduate Certificate/Diploma",
          "Tertiary - Master's Degree",
          "Tertiary - PhD",
          "Other (specify)"
        ]

eco_age = [
          "15-19",
          "20-24",
          "25-29",
          "30-34",
          "35-39",
          "40-44",
          "45-49",
          "50-54",
          "55-59",
          "60-64",
          "65-69",
          "70-74",
          "75-79",
          "80-84",
          "85-89",
          "90-94",
          "95-99",
          "100+"
]

all_ages = [
          "6-11",
          "12-14",
          "15-19",
          "20-24",
          "25-29",
          "30-34",
          "35-39",
          "40-44",
          "45-49",
          "50-54",
          "55-59",
          "60-64",
          "65-69",
          "70-74",
          "75-79",
          "80-84",
          "85-89",
          "90-94",
          "95-99",
          "100+"
]

child_edu = [
            "Never attended",
            "Nursery",
            "Kindergarten",
            "Primary",
            "JSS/JHS",
            "SSS/SHS",
            "Secondary",
            "Voc/technical/commercial"
]

eco_child_age = [
    "5-9",
    "10-14"
]

diff_age = [
    "5-9",
          "10-14",
          "15-17",
          "18-19",
          "20-24",
          "25-29",
          "30-34",
          "35-39",
          "40-44",
          "45-49",
          "50-54",
          "55-59",
          "60-64",
          "65-69",
          "70-74",
          "75-79",
          "80-84",
          "85-89",
          "90-94",
          "95-99",
          "100+"
]

edu_age = [
    "15-17 years",
            "15",
            "16",
            "17",
            "18 years & older",
            "18",
            "19",
            "20",
            "21",
            "22",
            "23",
            "24",
            "25",
            "26",
            "27",
            "28",
            "29",
            "30",
            "31",
            "32",
            "33",
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "51",
            "52",
            "53",
            "54",
            "55",
            "56",
            "57",
            "58",
            "59",
            "60",
            "61",
            "62",
            "63",
            "64",
            "65",
            "66",
            "67",
            "68",
            "69",
            "70",
            "71",
            "72",
            "73",
            "74",
            "75",
            "76",
            "77",
            "78",
            "79",
            "80",
            "81",
            "82",
            "83",
            "84",
            "85",
            "86",
            "87",
            "88",
            "89",
            "90",
            "91",
            "92",
            "93",
            "94",
            "95",
            "96",
            "97",
            "98",
            "99",
            "100+"
]

edu_sch_age = [
    "3-5 years",
          "3",
          "4",
          "5",
          "6-14 years",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15-17 years",
          "15",
          "16",
          "17",
          "18-19 years",
          "18",
          "19",
          "20-24 years",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25-29 years",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30 years & older"
]

















